<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>        <html class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>        <html class="no-js ie8"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>Clive example - Lists</title>
    <meta name="description" content="An example app for Clive">
    <meta name="author" content="Christian Kirkegaard">

    <!-- Mobile viewport optimized: j.mp/bplateviewport -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- CSS : implied media="all" -->
    <link rel="stylesheet" href="public/styles/style.css?v=2">

    <!-- All JavaScript at the bottom, except for Modernizr which enables HTML5 elements & feature detects -->
    <script src="public/scripts/libs/modernizr-1.6.min.js"></script>

</head>
<body lang="en">

    <div id="container">
        <header class="container_12">
            <div class="grid_12">
                <h1>Lists</h1>
            </div>
        </header>

        <div id="main" class="container_12" role="main">
            <?php print $content; ?>
        </div>

        <footer class="container_12">
            <div class="grid_12">
                <p>Build with <a href="http://github.com/ranza/clive/">Clive</a></p>
            </div>
        </footer>
    </div>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.5.0/jquery.js"></script>
    <script>!window.jQuery && document.write(unescape('%3Cscript src="public/scripts/libs/jquery-1.5.0.js"%3E%3C/script%3E'))</script>

    <script src="public/scripts/plugins.js"></script>
    <script src="public/scripts/script.js"></script>

    <!--[if lt IE 7 ]>
        <script src="public/scripts/libs/dd_belatedpng.js"></script>
        <script>DD_belatedPNG.fix('img, .png_bg'); // Fix any <img> or .png_bg bg-images. Also, please read goo.gl/mZiyb </script>
    <![endif]-->

</body>
</html>
